### ISSUE TITLE
sjsj: Command not found, Mac OS X

### ISSUE THREAD

**Issue by geoffdavis92** [hanksudo/SJSJ-cli#4]
I just installed the CLI using the steps in the README but upon restarting terminal, I cannot use the `sjsj` command; I get an error stating:

``` bash
-bash: sjsj: command not found
```

**Comment by hanksudo** [comment]
@geoffdavis92 Did you get any error message?

Can you please check you file `ls ~/bin/sjsj` is exists or not?

I guess maybe you don't have `~/bin` in your path, you can do:

``` bash
mkdir ~/bin
curl https://raw.githubusercontent.com/hanksudo/SJSJ-cli/master/sjsj > ~/bin/sjsj
chmod a+x ~/bin/sjsj
# add ~/bin to PATH
PATH=$PATH:~/bin
```
